title: OML Contracting Co
email: gary@omlhawaii.com
description: >
  In the realm of General Contracting and Construction Management,
  OML Contracting Co is dedicated to the care and needs of our clients
  and consultants. We’re here to Sheppard our client’s dreams, to transform
  two-dimensional visions into three-dimensional artistry, and to devote our
  time and means to the creation of spatial beauty.
baseurl: ""
url: "http://omlhawaii.com"

markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-titles-from-headings

collections:
  residences:
    output: true
    permalink: /gallery/:title/
  about:

sass:
  style: compressed

defaults:
 # - scope:
 #     path: ""
 #   values:

  - scope:
      path: ""
      type: residences
    values:
      layout: gallery
      images:
